apiVersion: v1
kind: ConfigMap
metadata:
  name: cpp-0-1-0-conda-env
data:
  conda-environment-definition.yaml: |
    name: cpp-env

    channels:
      - conda-forge
      - bioconda
      - defaults

    dependencies:
      - xeus-cling=0.11.0
      - xwidgets=0.24.2
      - xtensor=0.21.10
      - xtl=0.6.23
      - xframe=0.3.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cpp-0-1-0-modulefile
data:
  modulefile.lua: |
    help([[
    Conda environment with C++ kernels
    ]])

    whatis("Version: 0.1.0")
    whatis("Keywords: C++")

    prepend_path("JUPYTER_PATH", "/opt/modules/conda-envs/cpp-0.1.0/share/jupyter")
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cpp-0-1-0-installer-job
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      containers:
        - name: env-installer-test
          image: labshare/polyglot-notebook:env-installer-0.9.1
          command: ["sh", "-c"]
          args:
            - mkdir -p $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION;
              mamba env create --prefix $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION --file /home/jovyan/conda-environment-definition.yaml;
              mkdir -p $EXT_MOD_PATH/modulefiles/$ENV_MODULE_NAME;
              cp /home/jovyan/modulefile.lua $EXT_MOD_PATH/modulefiles/$ENV_MODULE_NAME/$ENV_MODULE_VERSION.lua
          env:
            - name: EXT_MOD_PATH
              value: /opt/modules
            - name: ENV_MODULE_NAME
              value: cpp
            - name: ENV_MODULE_VERSION
              value: 0.1.0
          volumeMounts:
            - mountPath: /opt/modules
              name: modules-volume
            - mountPath: /home/jovyan/conda-environment-definition.yaml
              name: conda-environment-definition
              subPath: conda-environment-definition.yaml
            - mountPath: /home/jovyan/modulefile.lua
              name: modulefile
              subPath: modulefile.lua
      restartPolicy: Never
      volumes:
        - name: modules-volume
          persistentVolumeClaim:
            claimName: modules-pv-claim
        - name: conda-environment-definition
          configMap:
            name: cpp-0-1-0-conda-env
            items:
              - key: conda-environment-definition.yaml
                path: conda-environment-definition.yaml
        - name: modulefile
          configMap:
            name: cpp-0-1-0-modulefile
            items:
              - key: modulefile.lua
                path: modulefile.lua
  backoffLimit: 4
