apiVersion: v1
kind: ConfigMap
metadata:
  name: imagej-converter-0-1-0-conda-env
data:
  conda-environment-definition.yaml: |
    name: imagej-converter-env

    channels:
      - conda-forge
      - bioconda
      - defaults
    dependencies:
      - pip
      - pyimagej=1.0.0
      - scyjava=1.1.0
      - jpype1=1.2.1
      - imglyb=1.0.0
      - black
      - cookiecutter
      - ipykernel
      - ipywidgets
      - python-kubernetes
      - pip:
        - bfio==2.1.9
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: imagej-converter-0-1-0-modulefile
data:
  modulefile.lua: |
    help([[
    Conda environment with packages to support ImageJ to plugin converter
    ]])

    whatis("Version: 0.1.0")
    whatis("Keywords: Data Science")

    prepend_path("JUPYTER_PATH", "/opt/modules/conda-envs/imagej-converter-0.1.0/share/jupyter")
---
apiVersion: batch/v1
kind: Job
metadata:
  name: imagej-converter-0-1-0-installer-job
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      containers:
        - name: env-installer-test
          image: labshare/polyglot-notebook:env-installer-0.9.1
          command: ["sh", "-c"]
          args:
            - mkdir -p $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION;
              mamba env create --prefix $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION --file /home/jovyan/conda-environment-definition.yaml;
              mkdir -p $EXT_MOD_PATH/modulefiles/$ENV_MODULE_NAME;
              cp /home/jovyan/modulefile.lua $EXT_MOD_PATH/modulefiles/$ENV_MODULE_NAME/$ENV_MODULE_VERSION.lua;
              mv $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/python3 $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/$ENV_MODULE_NAME;
              jq --arg variable "$KERNEL_DISPLAY_NAME" '.display_name = $variable' $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/$ENV_MODULE_NAME/kernel.json > tmp.$$.json && mv tmp.$$.json $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/$ENV_MODULE_NAME/kernel.json
          env:
            - name: EXT_MOD_PATH
              value: /opt/modules
            - name: ENV_MODULE_NAME
              value: imagej-converter
            - name: ENV_MODULE_VERSION
              value: 0.1.0
            - name: KERNEL_DISPLAY_NAME
              value: "ImageJ Converter 0.1.0"
          volumeMounts:
            - mountPath: /opt/modules
              name: modules-volume
            - mountPath: /home/jovyan/conda-environment-definition.yaml
              name: conda-environment-definition
              subPath: conda-environment-definition.yaml
            - mountPath: /home/jovyan/modulefile.lua
              name: modulefile
              subPath: modulefile.lua
      restartPolicy: Never
      volumes:
        - name: modules-volume
          persistentVolumeClaim:
            claimName: modules-pv-claim
        - name: conda-environment-definition
          configMap:
            name: imagej-converter-0-1-0-conda-env
            items:
              - key: conda-environment-definition.yaml
                path: conda-environment-definition.yaml
        - name: modulefile
          configMap:
            name: imagej-converter-0-1-0-modulefile
            items:
              - key: modulefile.lua
                path: modulefile.lua
  backoffLimit: 4
