apiVersion: v1
kind: ConfigMap
metadata:
  name: java-17-0-1-12-modulefile
data:
  modulefile.lua: |
    help([[
    Java
    ]])

    whatis("Version: 17.0.1")
    whatis("Keywords: Scientific/Engineering, Java")

    depends_on("maven")
    prepend_path("PATH", "/opt/modules/java-17.0.1_12/jdk-17.0.1+12/bin")
    setenv("JAVA_HOME", "/opt/modules/java-17.0.1_12/jdk-17.0.1+12")
    prepend_path("JUPYTER_PATH", "/opt/modules/java-17.0.1_12/share/jupyter")
---
apiVersion: batch/v1
kind: Job
metadata:
  name: java-17-0-1-12-installer-job
spec:
  template:
    spec:
      containers:
        - name: env-installer-test
          image: labshare/polyglot-notebook:env-installer-0.9.1
          command: ["sh", "-c"]
          args:
            - mkdir -p $EXT_MOD_PATH/$ENV_MODULE_NAME-$ENV_MODULE_VERSION;
              wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.1%2B12/OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz;
              tar xvf OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz -C $EXT_MOD_PATH/$ENV_MODULE_NAME-$ENV_MODULE_VERSION;
              mkdir -p $EXT_MOD_PATH/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels;
              wget https://github.com/SpencerPark/IJava/releases/download/v1.3.0/ijava-1.3.0.zip;
              unzip ijava-1.3.0.zip java/* -d $EXT_MOD_PATH/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels;
              jq --arg variable "$KERNEL_DISPLAY_NAME" --arg jar_exec "$EXT_MOD_PATH/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/java/ijava-1.3.0.jar" '.display_name = $variable | .argv[2] = $jar_exec' $EXT_MOD_PATH/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/java/kernel.json > tmp.$$.json && mv tmp.$$.json $EXT_MOD_PATH/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/java/kernel.json;
              wget https://raw.githubusercontent.com/FortAwesome/Font-Awesome/6.x/svgs/brands/java.svg -O $EXT_MOD_PATH/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/java/logo-64x64.svg;
              mkdir -p $EXT_MOD_PATH/modulefiles/$ENV_MODULE_NAME;
              cp /home/jovyan/modulefile.lua $EXT_MOD_PATH/modulefiles/$ENV_MODULE_NAME/$ENV_MODULE_VERSION.lua
          env:
            - name: EXT_MOD_PATH
              value: /opt/modules
            - name: ENV_MODULE_NAME
              value: java
            - name: ENV_MODULE_VERSION
              value: 17.0.1_12
            - name: KERNEL_DISPLAY_NAME
              value: "Java 17"
          volumeMounts:
            - mountPath: /opt/modules
              name: modules-volume
            - mountPath: /home/jovyan/modulefile.lua
              name: modulefile
              subPath: modulefile.lua
      restartPolicy: Never
      volumes:
        - name: modules-volume
          persistentVolumeClaim:
            claimName: modules-pv-claim
        - name: modulefile
          configMap:
            name: java-17-0-1-12-modulefile
            items:
              - key: modulefile.lua
                path: modulefile.lua
  backoffLimit: 4
