apiVersion: v1
kind: ConfigMap
metadata:
  name: julia-0-1-0-modulefile
data:
  modulefile.lua: |
    help([[
    Julia
    ]])

    whatis("Version: 0.1.0")
    whatis("Keywords: Scientific/Engineering, Julia")

    prepend_path("JULIA_DEPOT_PATH", "/opt/modules/julia-0.1.0/pkg")
    prepend_path("JUPYTER_PATH", "/opt/modules/julia-0.1.0/share/jupyter")
---
apiVersion: batch/v1
kind: Job
metadata:
  name: julia-0-1-0-installer-job
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      containers:
        - name: env-installer-test
          image: labshare/polyglot-notebook:env-installer-0.9.1
          command: ["sh", "-c"]
          args:
            - mkdir -p $EXT_MOD_PATH/$ENV_MODULE_NAME-$ENV_MODULE_VERSION;
              curl -fL -o julia.tar.gz "https://julialang-s3.julialang.org/bin/linux/x64/1.7/julia-1.7.2-linux-x86_64.tar.gz";
              tar -xzf julia.tar.gz -C $EXT_MOD_PATH/$ENV_MODULE_NAME-$ENV_MODULE_VERSION --strip-components 1;
              mkdir -p $EXT_MOD_PATH/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/pkg;
              $EXT_MOD_PATH/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/bin/julia -e 'import Pkg; Pkg.update(); Pkg.add([(;name="Feather"), (;name="DataFrames"), (;name="NamedArrays"), (;name="RDatasets"), (;name="IJulia"), (;name="InstantiateFromURL"), (;name="HDF5"), (;name="LanguageServer")])';
              mkdir -p $EXT_MOD_PATH/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/julia;
              mv /home/jovyan/.local/share/jupyter/kernels/julia-1.7/* $EXT_MOD_PATH/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/$ENV_MODULE_NAME;
              jq --arg kn "$KERNEL_DISPLAY_NAME" '.display_name = $kn' $EXT_MOD_PATH/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/$ENV_MODULE_NAME/kernel.json > tmp.$$.json && mv tmp.$$.json $EXT_MOD_PATH/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/$ENV_MODULE_NAME/kernel.json;
              mkdir -p $EXT_MOD_PATH/modulefiles/$ENV_MODULE_NAME;
              cp /home/jovyan/modulefile.lua $EXT_MOD_PATH/modulefiles/$ENV_MODULE_NAME/$ENV_MODULE_VERSION.lua
          env:
            - name: EXT_MOD_PATH
              value: /opt/modules
            - name: ENV_MODULE_NAME
              value: julia
            - name: ENV_MODULE_VERSION
              value: 0.1.0
            - name: KERNEL_DISPLAY_NAME
              value: "Julia 0.1.0"
            - name: JULIA_DEPOT_PATH
              value: /opt/modules/julia-0.1.0/pkg
          volumeMounts:
            - mountPath: /opt/modules
              name: modules-volume
            - mountPath: /home/jovyan/modulefile.lua
              name: modulefile
              subPath: modulefile.lua
      restartPolicy: Never
      volumes:
        - name: modules-volume
          persistentVolumeClaim:
            claimName: modules-pv-claim
        - name: modulefile
          configMap:
            name: julia-0-1-0-modulefile
            items:
              - key: modulefile.lua
                path: modulefile.lua
  backoffLimit: 4
