name: python-data-science-env

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.9
  - pip=21.3
  - pandas=1.3.3
  - blas=*=openblas
  - scikit-learn=1.0
  - scikit-image=0.18.3
  - sympy=1.8
  - cython=0.29.24
  - patsy=0.5.2
  - cloudpickle=1.6*
  - dill=0.3.4
  - statsmodels=0.12.2
  - dvc=2.7.4
  - beautifulsoup4=4.10*
  - xlrd=2*
  - numba=0.54*
  - sqlalchemy=1.4*
  - hdf5=1*
  - h5py=3*
  - gnuplot=5.4.1
  - bokeh=2.4.0
  - jupyter_bokeh=3.0.2
  - holoviews=1.14*
  - hvplot=0.7*
  - panel=0.12*
  - voila=0.2.15
  - plotly=5.3*
  - seaborn=0.11*
  - vincent=0.4*
  - altair=4.1*
  - vega_datasets=0.9*
  - bqplot=0.12*
  - pythreejs=2.3*
  - py4j=0.10.9
  - pyviz_comms=2.1*
  - pip:
    - opencv-python==4.5.3.56
    - tf-nightly-gpu==2.8.0.dev20210929
    - https://download.pytorch.org/whl/cu111/torch-1.9.1%2Bcu111-cp39-cp39-linux_x86_64.whl
    - https://download.pytorch.org/whl/cu111/torchvision-0.10.1%2Bcu111-cp39-cp39-linux_x86_64.whl
    - fastai==2.5.2
