apiVersion: v1
kind: ConfigMap
metadata:
  name: r-0-1-0-conda-env
data:
  conda-environment-definition.yaml: |
    name: R-env

    channels:
      - conda-forge
      - bioconda
      - defaults

    dependencies:
      - rpy2=3.4.5
      - r-arrow=5.0.0
      - r-irkernel=1.2
      - r-plyr=1.8.6
      - r-devtools=2.4.1
      - r-tidyverse=1.3.1
      - r-shiny=1.6.0
      - r-rmarkdown=2.8
      - r-forecast=8.14
      - r-rsqlite=2.2.5
      - r-reshape2=1.4.4
      - r-caret=6.0_88
      - r-rcurl=1.98_1.3
      - r-crayon=1.4.1
      - r-randomforest=4.6_14
      - r-htmltools=0.5.1.1
      - r-sparklyr=1.6.2
      - r-htmlwidgets=1.5.3
      - r-hexbin=1.28.2
      - r-feather=0.3.5
      - r-highcharter=0.8.2
      - r-dygraphs=1.1.1.6
      - r-visnetwork=2.0.9
      - r-d3heatmap=0.6.1.2
      - r-plotly=4.9.3
      - r-rbokeh=0.5.1
      - r-networkd3=0.4
      - r-dt=0.18
      - r-threejs=0.3.3
      - r-stringi=1.6.2
      - r-languageserver=0.3.10
      - sos-r=0.19.6
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: r-0-1-0-modulefile
data:
  modulefile.lua: |
    help([[
    Conda environment with R packages
    ]])

    whatis("Version: 0.1.0")
    whatis("Keywords: Scientific/Engineering, Software Development, R")


    set_alias("R", "/opt/modules/conda-envs/R-0.1.0/bin/R")
    prepend_path("JUPYTER_PATH", "/opt/modules/conda-envs/R-0.1.0/share/jupyter")
---
apiVersion: batch/v1
kind: Job
metadata:
  name: r-0-1-0-installer-job
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      containers:
        - name: env-installer-test
          image: labshare/polyglot-notebook:env-installer-0.9.1
          command: ["sh", "-c"]
          args:
            - mkdir -p $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION;
              mamba env create --prefix $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION --file /home/jovyan/conda-environment-definition.yaml;
              mv $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/ir $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/$ENV_MODULE_NAME;
              rm -rf $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/python3;
              rm -rf $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/sos;
              jq --arg kn "$KERNEL_DISPLAY_NAME" --arg r_exec "$EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/bin/R" '.display_name = $kn | .argv[0] = $r_exec' $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/$ENV_MODULE_NAME/kernel.json > tmp.$$.json && mv tmp.$$.json $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/$ENV_MODULE_NAME/kernel.json;
              mkdir -p $EXT_MOD_PATH/modulefiles/$ENV_MODULE_NAME;
              cp /home/jovyan/modulefile.lua $EXT_MOD_PATH/modulefiles/$ENV_MODULE_NAME/$ENV_MODULE_VERSION.lua
          env:
            - name: EXT_MOD_PATH
              value: /opt/modules
            - name: ENV_MODULE_NAME
              value: R
            - name: ENV_MODULE_VERSION
              value: 0.1.0
            - name: KERNEL_DISPLAY_NAME
              value: "R 0.1.0"
          volumeMounts:
            - mountPath: /opt/modules
              name: modules-volume
            - mountPath: /home/jovyan/conda-environment-definition.yaml
              name: conda-environment-definition
              subPath: conda-environment-definition.yaml
            - mountPath: /home/jovyan/modulefile.lua
              name: modulefile
              subPath: modulefile.lua
      restartPolicy: Never
      volumes:
        - name: modules-volume
          persistentVolumeClaim:
            claimName: modules-pv-claim
        - name: conda-environment-definition
          configMap:
            name: r-0-1-0-conda-env
            items:
              - key: conda-environment-definition.yaml
                path: conda-environment-definition.yaml
        - name: modulefile
          configMap:
            name: r-0-1-0-modulefile
            items:
              - key: modulefile.lua
                path: modulefile.lua
  backoffLimit: 4
