apiVersion: v1
kind: ConfigMap
metadata:
  name: test-0-1-0-conda-env
data:
  conda-environment-definition.yaml: |
    name: test-env

    channels:
      - conda-forge
      - bioconda
      - defaults

    dependencies:
      - python=3.9
      - pip=21.3
      - ipykernel=6.9.0
      - pandas=1.3.3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-0-1-0-modulefile
data:
  modulefile.lua: |
    help([[Test environment]])

    whatis("Version: 0.1.0")
    whatis("Keywords: Test")

    prepend_path("JUPYTER_PATH", "/opt/modules/conda-envs/test-0.1.0/share/jupyter")
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-0-1-0-installer-job
spec:
  template:
    spec:
      containers:
        - name: env-installer-test
          image: labshare/polyglot-notebook:env-installer-0.9.1
          command: ["sh", "-c"]
          args:
            - mkdir -p $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION;
              mamba env create --prefix $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION --file /home/jovyan/conda-environment-definition.yaml;
              mkdir -p $EXT_MOD_PATH/modulefiles/$ENV_MODULE_NAME;
              cp /home/jovyan/modulefile.lua $EXT_MOD_PATH/modulefiles/$ENV_MODULE_NAME/$ENV_MODULE_VERSION.lua;
              mv $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/python3 $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/test;
              jq --arg variable "$KERNEL_DISPLAY_NAME" '.display_name = $variable' $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/test/kernel.json > tmp.$$.json && mv tmp.$$.json $EXT_MOD_PATH/conda-envs/$ENV_MODULE_NAME-$ENV_MODULE_VERSION/share/jupyter/kernels/test/kernel.json
          env:
            - name: EXT_MOD_PATH
              value: /opt/modules
            - name: ENV_MODULE_NAME
              value: test
            - name: ENV_MODULE_VERSION
              value: 0.1.0
            - name: KERNEL_DISPLAY_NAME
              value: "Test 0.1.0"
          volumeMounts:
            - mountPath: /opt/modules
              name: modules-volume
            - mountPath: /home/jovyan/conda-environment-definition.yaml
              name: conda-environment-definition
              subPath: conda-environment-definition.yaml
            - mountPath: /home/jovyan/modulefile.lua
              name: modulefile
              subPath: modulefile.lua
      restartPolicy: Never
      volumes:
        - name: modules-volume
          persistentVolumeClaim:
            claimName: modules-pv-claim
        - name: conda-environment-definition
          configMap:
            name: test-0-1-0-conda-env
            items:
              - key: conda-environment-definition.yaml
                path: conda-environment-definition.yaml
        - name: modulefile
          configMap:
            name: test-0-1-0-modulefile
            items:
              - key: modulefile.lua
                path: modulefile.lua
  backoffLimit: 4
