apiVersion: v2
name: polus-jupyterhub
description: Polus JupyterHub
type: application
version: 0.2.0
dependencies:
  - name: postgresql
    version: ~11.6.7
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
appVersion: 0.9.0
