# Global configurations for PostgreSQL dependency
global:
  # Preconfigured Kubernetes Storage Class
  storageClass: aws-efs

hub:
  image:
    name: labshare/jupyterhub
    tag: "0.8.1.18"

  notebookVersion: 0.9.0

  storage:
    storageClass: aws-efs
    storagePerUser: 1Gi
    sharedNotebooksStorage: 5Gi
    modulesStorage: 100Gi
    sharedNotebooksClaimName: shared-notebooks-pv-claim
    modulesClaimName: modules-pv-claim

  wipp:
    enabled: false
    storageClaimName: wipp-pv-claim
    mountPath: /opt/shared/wipp
    apiURL: http://wipp-backend:8080/api
    UIValue: https://wipp-ui.ci.aws.labshare.org
    tempNotebooksRelPath: temp/notebooks
    tempPluginsRelPath: temp/plugins
  
  polusNotebooksHub:
    enabled: false
    apiURL: https://polus-notebooks-hub-backend.ci.aws.labshare.org

# Configurations for PostgreSQL dependency
postgresql:
  enabled: true
  postgresqlDatabase: postgresd
  postgresqlUsername: blablabla
  postgresqlPassword: hahahaha
  persistence:
    size: 1Gi