hub:
  image:
    name: labshare/jupyterhub
    tag: "0.8.1.18"

  notebookVersion: 0.9.0

  storage:
    storageClass: aws-efs
    storagePerUser: 1Gi
    sharedNotebooksStorage: 5Gi
    modulesStorage: 100Gi
    sharedNotebooksClaimName: shared-notebooks-pv-claim
    modulesClaimName: modules-pv-claim
  
  db:
    type: postgres
    user:
    password:

  wipp:
    enabled: false
    storageClaimName: wipp-pv-claim
    mountPath: /opt/shared/wipp
    apiURL: http://wipp-backend:8080/api
    UIValue: https://wipp-ui.ci.aws.labshare.org
    tempNotebooksRelPath: temp/notebooks
    tempPluginsRelPath: temp/plugins
  
  polusNotebooksHub:
    enabled: false
    apiURL: https://polus-notebooks-hub-backend.ci.aws.labshare.org