# Global chart configuration
global:
  # Preconfigured Kubernetes Storage Class
  storageClass: aws-efs

hub:
  image:
    name: labshare/jupyterhub
    tag: "0.8.2.3"

  notebookVersion: 0.9.1

  storage:
    storagePerUser: 1Gi
    sharedNotebooksStorage: 5Gi
    modulesStorage: 100Gi
    sharedNotebooksClaimName: shared-notebooks-pv-claim
    modulesClaimName: modules-pv-claim
  
  # JupyterHub external Service configuration
  service:
    # Kubernetes Service type (NodePort, ClusterIP, LoadBalancer, ExternalName)
    type: LoadBalancer

  # JupyterHub Ingress configuration for external access, uses Nginx Ingress by default
  # TODO: Enable configuration for alternative Ingress solutions  
  ingress:
    # Using Ingress is optional and requires preconfiguration within the cluster
    enabled: false
    # Host name for external access
    hostName: null
  
  # LabShare Auth configurations
  auth:
    enabled: false
    # Auth service url
    url: null
    # Unique tenant configured in LS-Auth
    tenant: null
    # Unique client ID configured in the above tenant
    clientID: null
    clientSecret: null
    callbackURL: null
    adminUsers: null
    

  wipp:
    enabled: false
    storageClaimName: wipp-pv-claim
    mountPath: /opt/shared/wipp
    apiURL: http://wipp-backend:8080/api
    UIValue: null
    tempNotebooksRelPath: temp/notebooks
    tempPluginsRelPath: temp/plugins
  
  polusNotebooksHub:
    enabled: false
    apiURL: null

# Configurations for PostgreSQL dependency
postgresql:
  enabled: true
  auth:
    database: postgresd
    username: postgres
    password: postgres
  persistence:
    size: 1Gi