FROM labshare/polyglot-notebook:NOTEBOOKS_DEPLOY_TAG_VALUE

# Install easybuild
ENV EASYBUILD_PREFIX=/opt/modules \
    EASYBUILD_BUILDPATH=/tmp/easybuild
RUN pip install --ignore-installed easybuild==4.5.1
