FROM labshare/polyglot-notebook:NOTEBOOK_VERSION_DEPLOY_VALUE

# Install easybuild
ENV EASYBUILD_PREFIX=/opt/modules \
    EASYBUILD_BUILDPATH=/tmp/easybuild
RUN pip install --ignore-installed easybuild==4.5.1
