apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jupyterhub.hub.fullname" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
data:
  {{- /*
    Glob files to allow them to be mounted by the hub pod

    jupyterhub_config: |
      multi line string content...
    z2jh.py: |
      multi line string content...
  */}}
  {{- (.Files.Glob "files/hub/*").AsConfig | nindent 2 }}
