{{- if .Values.hub.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  name: {{ include "jupyterhub.ingress.fullname" . }}
spec:
  rules:
    - host: {{ .Values.hub.ingress.hostName }}
      http:
        paths:
          - backend:
              serviceName: jupyterhub
              servicePort: 80
            path: /
{{- end }}