apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jupyterhub.fullname" . }}-hub
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "jupyterhub.fullname" . }}-hub
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "jupyterhub.fullname" . }}-hub
subjects:
  - kind: ServiceAccount
    name: {{ include "jupyterhub.fullname" . }}-hub
roleRef:
  kind: Role
  name: {{ include "jupyterhub.fullname" . }}-hub
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jupyterhub.fullname" . }}-user
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "jupyterhub.fullname" . }}-user
rules:
  - apiGroups:
    - argoproj.io
    resources:
    - workflows
    verbs:
    - delete
    - deletecollection
    - get
    - list
    - patch
    - create
    - update
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "jupyterhub.fullname" . }}-user
subjects:
- kind: ServiceAccount
  name:  {{ include "jupyterhub.fullname" . }}-user
roleRef:
  kind: Role
  name: {{ include "jupyterhub.fullname" . }}-user
  apiGroup: rbac.authorization.k8s.io