kind: Secret
apiVersion: v1
metadata:
  name: {{ include "jupyterhub.hub.fullname" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
type: Opaque
data:
    {{- $values := merge dict .Values }}
    {{- /* also passthrough subset of Chart / Release */}}
    {{- $_ := set $values "Chart" (dict "Name" .Chart.Name "Version" .Chart.Version) }}
    {{- $_ := set $values "Release" (pick .Release "Name" "Namespace" "Service") }}
    values.yaml: {{ $values | toYaml | b64enc | quote }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "jupyterhub.hub.fullname" . }}-admin-token
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
type: Opaque
data:
  adminToken: {{ randAlphaNum 32 | b64enc | quote }}