name: R
apt:
  - fonts-dejavu
  - gfortran
  - gcc
  - libicu-dev
conda:
  - rpy2: 3.4.5
  - r-irkernel: 1.2
  - r-plyr: 1.8.6
  - r-devtools: 2.4.1
  - r-tidyverse: 1.3.1
  - r-shiny: 1.6.0
  - r-rmarkdown: 2.8
  - r-forecast: 8.14
  - r-rsqlite: 2.2.5
  - r-reshape2: 1.4.4
  - r-caret: "6.0_88"
  - r-rcurl: "1.98_1.3"
  - r-crayon: 1.4.1
  - r-randomforest: "4.6_14"
  - r-htmltools: 0.5.1.1
  - r-sparklyr: 1.6.2
  - r-htmlwidgets: 1.5.3
  - r-hexbin: 1.28.2
  - r-feather: 0.3.5
  - r-highcharter: 0.8.2
  - r-dygraphs: 1.1.1.6
  - r-visnetwork: 2.0.9
  - r-d3heatmap: 0.6.1.2
  - r-plotly: 4.9.3
  - r-rbokeh: 0.5.1
  - r-networkd3: 0.4
  - r-dt: 0.18
  - r-threejs: 0.3.3
  - r-rglwidget: 0.2.1
  - r-stringi: 1.6.2
  - sos-r: 0.19.6