#################################################################################################################
# Create PVC for shared notebook storage
#################################################################################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notebooks-pv-claim
spec:
  storageClassName: STORAGE_CLASS_VALUE
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: SHARED_STORAGE_VALUE
