#################################################################################################################
# Create StorageClass for using PVCs with Rook/Ceph
#################################################################################################################
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-block
provisioner: ceph.rook.io/block
parameters:
  blockPool: replicapool
  # The value of "clusterNamespace" MUST be the same as the one in which your rook cluster exist
  clusterNamespace: rook-ceph
  # Specify the filesystem type of the volume. If not specified, it will use `ext4`.
  fstype: xfs
# Optional, default reclaimPolicy is "Delete". Other options are: "Retain", "Recycle" as documented in https://kubernetes.io/docs/concepts/storage/storage-classes/
reclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    name: shared-volume
  name: shared-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: STORAGE_SHARED_VALUE
  flexVolume:
    driver: ceph.rook.io/rook
    fsType: ceph
    options:
      clusterNamespace: rook-ceph
      fsName: myfs
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rook-ceph-block

---
# PVC for shared filesystem for all Jupyter users
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pv-claim
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteMany
  selector:
    matchLabels:
      name: shared-volume
  resources:
    requests:
      storage: STORAGE_SHARED_VALUE