name: Python-Datascience
conda:
  - pandas: 1.3.3
  - blas: "*=openblas"
  - scikit-learn: 1.0
  - scikit-image: 0.18.3
  - sympy: 1.8
  - cython: 0.29.24
  - patsy: 0.5.2
  - cloudpickle: 1.6*
  - dill: 0.3.4
  - statsmodels: 0.12.2
  - dvc: 2.7.4
  - beautifulsoup4: 4.10*
  - xlrd: 2*
  - numba: 0.54*
  - sqlalchemy: 1.4*
  - hdf5: 1*
  - h5py: 3*
pip:
  - opencv-python: 4.5.3.56