name: Scala
env:
  - SCALA_VERSION: 2.13
  - ALMOND_VERSION: 0.11.1
pip:
  - sos-scala: 0.18.0
scripts:
  - scala: |
      curl -Lo coursier https://git.io/coursier-cli && \
      chmod +x coursier && \
      ./coursier launch --fork almond:$ALMOND_VERSION --scala $SCALA_VERSION -- --install && \
      rm coursier