name: Build Docker image

on:
  push:
    branches:
      - main
      - feature/github-actions-docker-build
  pull_request:
    branches: [ master ]
    types: [closed]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Assemble Notebook Dockerfile
      run: |
        npm install -g polus-railyard@0.3.2
        mkdir -p manifests
        railyard assemble -t Dockerfile.template -b base.yaml -a values.yaml -p manifests
        ls -la manifests
        dir=$(find manifests -mindepth 1 -maxdepth 1 -type d)
        echo "$dir"
        echo "docker_context=deploy/docker/notebook/$dir" >> $GITHUB_ENV
      working-directory: deploy/docker/notebook
    
    - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.POLUS_DOCKER_USERNAME }}
          password: ${{ secrets.POLUS_DOCKER_TOKEN }}

    - name: Build Notebook Docker image
      uses: docker/build-push-action@v2
      with:
          context: ${{ env.docker_context }}
          push: true
          tags: labshare/polyglot-notebook:latest