name: Build Docker images

on:
  push:
    branches:
    paths:
    - 'deploy/docker/jupyterhub/VERSION'
  pull_request:
    branches: [ master ]
    types: [closed]
    paths:
    - 'deploy/docker/jupyterhub/VERSION'

jobs:

  jupyterhub-docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get JupyterHub Version
      run: echo "jupyterhub_version=`cat deploy/docker/jupyterhub/VERSION`" >> $GITHUB_ENV
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: polusbot
        password: ${{ secrets.POLUS_DOCKER_TOKEN }}

    - name: Build JupyterHub Docker image
      uses: docker/build-push-action@v2
      with:
          context: deploy/docker/jupyterhub
          push: true
          tags: labshare/jupyterhub:${{ env.jupyterhub_version }}